### PR TITLE
Use lsp-protocol and plists

### PR DESCRIPTION
**Pull request by ericdallo**
https://github.com/emacs-lsp/lsp-mode/issues/1751

Depends on https://github.com/emacs-lsp/lsp-mode/pull/1747

### CODE REVIEW

**Comment by sebastiansturm** [comment]
thanks alot! Will gladly merge this as is, though I guess I should first do a versioned release that works with lsp-mode 6.3.1 so users can still install something functional from melpa stable.
A few docstrings explicitly refer to hash tables being passed around, are those parts still correct?

**Comment by ericdallo** [comment]
@sebastiansturm, fixed the docstring, I think we can merge this as emacs-lsp/lsp-mode#1747 was merged today and it doesn't need anything more to work, what do you think?

**Comment by sebastiansturm** [comment]
yes, I think so too. I created a 0.3 tag so I think the merge shouldn't affect users of melpa/stable. Thanks again!

**Comment by ericdallo** [comment]
Thank you!

**Pull request merged**
