### PR TITLE
Use ivy-update-candidates

### PR DESCRIPTION
**Pull request by abo-abo**

### CODE REVIEW

**Comment by abo-abo** [comment]
This needs the latest swiper (78dd554).

**Comment by sebastiansturm** [comment]
thanks alot! Works excellently on my machine, and the code looks cleaner now than it used to. I haven't merged it yet because I'm worried it might break for people using stable package versions. Is there a version 0.13.0 of ivy/swiper right around the corner that will include the new API? Or should I perhaps include the old implementation as a fallback and select that based on the availability of `ivy-update-candidates` until a new stable version is available? I also have a minor question regarding the API, but I'm taking that over to abo-abo/swiper#2263

**Comment by abo-abo** [comment]
I'll try to release 0.13.0 within a month.

**Comment by yyoncho** [comment]
@sebastiansturm 

> I'm worried it might break for people using stable package versions. 

lsp-ivy will be in melpa so our expectation is users to use the latest melpa version of all deps.

**Comment by abo-abo** [comment]
Ivy-0.13.0 is now released. GNU ELPA build process should not take more than a day.

**Comment by yyoncho** [comment]
@abo-abo thank you!

**Comment by sebastiansturm** [comment]
great! will merge the PR then later this evening

**Pull request merged**
